package vue;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import controleur.statistiqueNote;
import modele.Connecter;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.Dimension;

public class gestionCollection extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_de_la_collection
     */
	Connecter conn=new Connecter();
	Statement stm;
	ResultSet Rs;
	DefaultTableModel model=new DefaultTableModel();


	String id;
    String titre;
    String auteur;
    String status;
    String nbrTome;
    
    public gestionCollection(String id, String titre, String auteur, String status, String nbrTome)
			throws HeadlessException {
		super();
		this.id = id;
		this.titre = titre;
		this.auteur = auteur;
		this.status = status;
		this.nbrTome = nbrTome;
	}
    
    public gestionCollection() {
    	  	
        initComponents();
        
        model.addColumn("id");
        model.addColumn("Titre");
        model.addColumn("Auteur");
        model.addColumn("Status");
        model.addColumn("NbrTome");
        try {
        	stm=conn.obtenirconnexion().createStatement();
        	ResultSet Rs=stm.executeQuery("Select * from manga");
        	while(Rs.next()) {
        		model.addRow(new Object[] {Rs.getString("id"),Rs.getString("Titre"),Rs.getString("Auteur"),
        				Rs.getString("Status"),Rs.getString("NbrTome")});	
        	}
        } catch(Exception e){
        	System.err.println(e);
        	}
        tble.setModel(model);
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
 
    
    public void deplace(int i) {
    	try {
    		txtid.setText(model.getValueAt (i, 0).toString());
    		txtno.setText(model.getValueAt (i, 1).toString());
    		txtpr.setText(model.getValueAt (i, 2).toString());
    		txtbr.setSelectedItem(model.getValueAt (i, 3).toString());
    		txtnot.setText(model.getValueAt (i, 4).toString());

    	}catch (Exception e){
    		System.err.println(e);
    		JOptionPane.showMessageDialog(null , "erreur de déplacement"+e.getLocalizedMessage());
    	}
    }
    
    
    public void affiche() {
    	try {
    		model.setRowCount(0);
        	stm=conn.obtenirconnexion().createStatement();
        	ResultSet Rs=stm.executeQuery("Select * from manga");
        	while(Rs.next()) {
        		model.addRow(new Object[] {Rs.getString("id"),Rs.getString("Titre"),Rs.getString("Auteur"),
        				Rs.getString("Status"),Rs.getString("NbrTome")});	
        	}
        } catch(Exception e){
        	System.err.println(e);
        	}
        tble.setModel(model);
    }
    
    //affiche valeurs quand on clique dans le tableau.
    public void tbleMouseClicked(java.awt.event.MouseEvent evt) {
    	try{
    		int i=tble.getSelectedRow();
    		deplace(i);
    	}catch(Exception e){
    		JOptionPane.showMessageDialog(null,"erreur de deplacement "+e.getLocalizedMessage());}
    		}
    
    //bouton AJOUTER
    public void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        id=txtid.getText();
        titre=txtno.getText();
        auteur=txtpr.getText();
        status=txtbr.getSelectedItem().toString();
        nbrTome=txtnot.getText();
        String requete="insert into manga(id,Titre,Auteur,Status,NbrTome)VALUES('"+
                id+"','"+titre+"','"+auteur+"','"+status+"','"+nbrTome+"')";
        try{
        	stm.executeUpdate(requete);
        	JOptionPane.showMessageDialog(null,"Le manga a bien été ajouter à la collection");
        	txtid.setText(id);
        	txtno.setText("");
        	txtpr.setText("");txtbr.setSelectedItem(0);txtnot.setText("");
        	affiche();
        }catch(Exception ex){
        	JOptionPane.showMessageDialog(null,"l'id est déjà utilisé pour un autre manga de la collection !!!"); //+ex.getMessage()
        	}
    }
    
    //bouton ACTUALISER
    public void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
    	affiche();
    }
    
    //bouton MODIFIER
    public void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
    	try { 
    	            if (JOptionPane.showConfirmDialog (null,"confirmer la modification","modification",
    	                    JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {

    	                stm.executeUpdate("UPDATE manga SET Titre='"+txtpr.getText()+"',Auteur='"+txtpr.getText()+
    	                		"',NbrTome='"+txtnot.getText()+
    	                        "',Status='"+txtbr.getSelectedItem().toString()+
    	                        "' WHERE id= "+txtid.getText());   
    	                affiche();
    	            } 
    	        } catch (Exception e){JOptionPane.showMessageDialog(null,"erreur de modification !!!"+e.getMessage());
    	        System.err.println(e);}
    	    }
    
    
    //bouton SUPPRIMER
    public void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    	try {
    	            if(JOptionPane.showConfirmDialog(null,"voulez vous vraiment supprimer ce manga de votre collection ?"
    	                     ,"supprimer manga",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
    	            if(txtid.getText().length() != 0){
    	        stm.executeUpdate("Delete From manga where id = "+txtid.getText());
    	        affiche();
    	             }
    	            else { JOptionPane.showMessageDialog(null,"veuillez SVP remplire le champ id !");}
    	        
    	        }catch (Exception e){JOptionPane.showMessageDialog(null,"erreur de suppression \n"+e.getMessage());} 
    	    }
    //bouton STATISTIQUE
    public void jButton6MouseClicked(java.awt.event.MouseEvent evt) {
    	statistiqueNote a=new statistiqueNote();
    	a.setVisible(true);
    }
    //bouton RECHERCHE MANGA
    public void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
    	try {
    	           model.setRowCount(0);// pour vider la list des mangas
    	      {	
    	       Rs = stm.executeQuery("Select * From manga WHERE Titre = '"+txtre.getText()+"'");
    	       }while (Rs.next()){
    	       
    	       Object [] manga ={Rs.getInt(1),Rs.getString(2),Rs.getString(3),Rs.getInt(4),Rs.getString(5)};
    	     model.addRow(manga);
    	       } if (model.getRowCount () == 0){JOptionPane.showMessageDialog(null,"Aucun manga ne correspond a ce titre dans la collection !");
    	       
    	       } else{ int i=0;
    	       deplace(i);
    	       }
    	       
    	       }catch (Exception e) { System.err.println(e);
    	       JOptionPane.showMessageDialog(null,e.getMessage());
       }
    	    
    }
    
  //bouton RECHERCHE AUTEUR
    public void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
    	try {
    	           model.setRowCount(0);// pour vider la list des mangas
    	      {
    	       Rs = stm.executeQuery("Select * From manga WHERE Auteur = '"+txtre.getText()+"'");
    	       }while (Rs.next()){
    	       
    	       Object [] manga ={Rs.getInt(1),Rs.getString(2),Rs.getString(3),Rs.getInt(4),Rs.getString(5)};
    	     model.addRow(manga);
    	       } if (model.getRowCount () == 0){JOptionPane.showMessageDialog(null,"Aucun manga ne correspond a cet auteur dans la collection !");
    	       
    	       } else{ int i=0;
    	       deplace(i);
    	       }
    	       
    	       }catch (Exception e) { System.err.println(e);
    	       JOptionPane.showMessageDialog(null,e.getMessage());
       }
    	    
    }
    
    
    //bouton RECHERCHE 2
    public void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
    	try {
    	           model.setRowCount(0);// pour vider la liste des mangas
    	      {
    	       Rs = stm.executeQuery("Select * From manga WHERE Status = '"+txtre2.getSelectedItem()+"'");
    	       }while (Rs.next()){
    	       
    	       Object [] manga2 ={Rs.getInt(1),Rs.getString(2),Rs.getString(3),Rs.getInt(4),Rs.getString(5)};
    	       model.addRow(manga2);
    	       
    	       } if (model.getRowCount () == 0){JOptionPane.showMessageDialog(null,"Aucun manga ne correspond a ce status dans la collection !");
    	       
    	       } else{ int i=0;
    	       deplace(i);
    	       }
    	       
    	       }catch (Exception e) { System.err.println(e);
    	       JOptionPane.showMessageDialog(null,e.getMessage());
       }
    }
          
    
    public void initComponents() {
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        	}
        });
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        txtre = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        txtre2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent arg0) {
        	}
        });
        tble = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnot = new javax.swing.JTextField();
        txtbr = new javax.swing.JComboBox();
        txtpr = new javax.swing.JTextField();
        txtno = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(970, 630));
        setLocation(300, 200);
        getContentPane().setLayout(null);

        jButton1.setFont(new Font("Tahoma", Font.BOLD, 14)); 
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supprimer.png"))); 
        jButton1.setText("Supprimer");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1);
        jButton1.setBounds(502, 299, 155, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); 
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajouter.png"))); 
        jButton2.setText("Ajouter");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton2);
        jButton2.setBounds(244, 299, 130, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); 
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rechercher.png"))); 
        jButton3.setText("manga");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });      
        getContentPane().add(jButton3);
        jButton3.setBounds(244, 215, 119, 40);
        
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); 
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rechercher.png"))); 
        jButton9.setText("auteur");
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setFocusPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });       
        getContentPane().add(jButton9);
        jButton9.setBounds(244, 258, 119, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); 
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/actualiser.png"))); 
        //jButton4.setText("Actualiser");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        
        getContentPane().add(jButton4);
        jButton4.setBounds(796, 299, 60, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); 
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/modifier.png"))); 
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.setText("Modifier");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton5);
        jButton5.setBounds(375, 299, 129, 40);
        
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14));  
        jButton6.setText("Statistique");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/stat.png")));         
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        
        getContentPane().add(jButton6);
        jButton6.setBounds(654, 299, 155, 40);
        
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); 
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rechercher.png"))); 
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        //jButton7.setText("recherche - status");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
       
        getContentPane().add(jButton7);
        jButton7.setBounds(255, 162, 42, 40);

        txtre.setFont(new java.awt.Font("Tahoma", 0, 14)); 
        getContentPane().add(txtre);
        txtre.setBounds(361, 242, 130, 30);
        
        txtre2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "enCours", "terminer" }));
        getContentPane().add(txtre2);
        txtre2.setBounds(309, 172, 130, 30);

        jLabel6.setFont(new Font("Times New Roman", Font.BOLD, 55)); 
        jLabel6.setText("Biblioth\u00E8que Manga");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(37, 13, 594, 82);

        tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        
        tble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleMouseClicked(evt);
            }
        });
        
        jScrollPane1.setViewportView(tble);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(37, 357, 858, 113);

        jLabel2.setFont(new Font("Times New Roman", Font.BOLD, 22)); 
        jLabel2.setText("id :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(37, 138, 42, 17);

        jLabel1.setFont(new Font("Times New Roman", Font.BOLD, 20)); 
        jLabel1.setText("Titre :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(37, 185, 60, 17);

        jLabel3.setFont(new Font("Times New Roman", Font.BOLD, 20)); 
        jLabel3.setText("Auteur :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(37, 226, 74, 17);

        jLabel4.setFont(new Font("Times New Roman", Font.BOLD, 20)); 
        jLabel4.setText("Status :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(37, 269, 74, 17);

        jLabel5.setFont(new Font("Times New Roman", Font.BOLD, 20)); 
        jLabel5.setText("nbrTome  :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(37, 312, 111, 17);
        
        txtnot.setFont(new java.awt.Font("Tahoma", 0, 14)); 
        getContentPane().add(txtnot);
        txtnot.setBounds(139, 308, 100, 23);

        txtbr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "enCours", "terminer" }));
        getContentPane().add(txtbr);
        txtbr.setBounds(115, 266, 100, 22);

        txtpr.setFont(new java.awt.Font("Tahoma", 0, 14)); 
        getContentPane().add(txtpr);
        txtpr.setBounds(115, 222, 100, 23);

        txtno.setFont(new java.awt.Font("Tahoma", 0, 14)); 
        getContentPane().add(txtno);
        txtno.setBounds(115, 181, 100, 23);

        txtid.setFont(new java.awt.Font("Tahoma", 0, 14)); 

        getContentPane().add(txtid);
        txtid.setBounds(115, 134, 100, 23);

        
        
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wallp2.jpg"))); 
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -63, 964, 646);

        pack();
        
    }

    //public static void main(String args[]) {
    //	java.awt.EventQueue.invokeLater(new Runnable() {
    //        public void run() {
    //        	openSplashScreen();
                //new gestionCollection().setVisible(true);
    //        }
    //    });
    //}
    
    // Variables declaration
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    public javax.swing.JButton jButton7;
    public javax.swing.JButton jButton9;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tble;
    public javax.swing.JComboBox txtbr;
    public javax.swing.JTextField txtid;
    public javax.swing.JTextField txtno;
    public javax.swing.JTextField txtnot;
    public javax.swing.JTextField txtpr;
    public javax.swing.JTextField txtre;
    public javax.swing.JComboBox txtre2;
    
    
    public String getTitre() {
		return titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public String getAuteur() {
		return auteur;
	}

	public void setAuteur(String auteur) {
		this.auteur = auteur;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getNbrTome() {
		return nbrTome;
	}

	public void setNbrTome(String nbrTome) {
		this.nbrTome = nbrTome;
	}
	
    @Override
	public String toString() {
		return "gestionCollection [id=" + id + ", titre=" + titre + ", auteur=" + auteur + ", status=" + status
				+ ", nbrTome=" + nbrTome + "]";
	}

}
