package vue;

import javax.swing.JFrame;
import javax.swing.GroupLayout.Alignment;

import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

public class statistique extends JFrame{
	
	/**
     * @param args the command line arguments
     */	
	public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;

    /**
     * Creates new form statistique
     */

    public statistique() {
        initComponents();     
	      
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    public void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); 
        jLabel8.setText("nbr de manga en cours :");
        jLabel9 = new javax.swing.JLabel();
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); 
        jLabel9.setText("nbr de manga terminer :");
        jLabel10 = new javax.swing.JLabel();
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); 
        jLabel10.setText("nbr de tome :");
        
        jLabel11 = new javax.swing.JLabel();
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); 
        jLabel11.setText("");
        jLabel12 = new javax.swing.JLabel();
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); 
        jLabel12.setText("");
        jLabel13 = new javax.swing.JLabel();
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); 
        jLabel13.setText("");
        
        jLabel14 = new javax.swing.JLabel();
        
        
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wallp2.jpg"))); 
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, -63, 964, 643);
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jLabel10, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jLabel8, GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jLabel12, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jLabel13, GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
        					.addGap(20))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabel11, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addContainerGap())))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(20)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
        			.addGap(20)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(20)
        					.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(20, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);
        setLocation(350, 300);
        pack();
        
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wallp2.jpg"))); 
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, -63, 964, 643);
    }  
   

}
